language: csharp
solution: jigsaw.sln
matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      env: DOTNETCORE=1
    - mono: latest
install:
  - nuget restore jigsaw.sln
script:
  - xbuild /p:Configuration=Release jigsaw.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TestLogicPuzzle/bin/Release/TestLogicPuzzle.dll