language: csharp
solution: jigsaw.sln
dotnet: 1.0.1
mono: none
dist: trusty
install:
  - dotnet restore jigsaw.sln
script:
  - cd TestLogicPuzzle
  - dotnet test
notifications:
  email:
    on_success: never
    on_failure: change